[package]
name = "hmac-drbg"
version = "0.1.2"
authors = ["Wei Tang <hi@that.world>"]
description = "Pure Rust implementation of Hmac DRBG."
license = "Apache-2.0"

[dependencies]
generic-array = "0.12"
hmac = { git = "https://github.com/mesalock-linux/rustcrypto-MACs-sgx", tag = "sgx_1.0.9" }

[dev-dependencies]
#sha2 = "0.6"
#etcommon-hexutil = "0.2"
#typenum = "1.9"
#serde = "1.0"
#serde_derive = "1.0"
#serde_json = "1.0"
